server:
  port: 9004
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/certification_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
    redis:
      host: 37.60.239.221
      port: 6379
      timeout: 300000
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER:https://oauth2-server.synthi-ai.com}
  kafka:
    consumer:
      group-id: certification-service-group
      properties:
        spring.json.trusted.packages: com.i4u.synthi_ai.*
    listener:
      concurrency: 3
      ack-mode: MANUAL_IMMEDIATE
      missing-topics-fatal: false
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      properties: null
  task:
    execution:
      pool:
        core-size: 10
        max-size: 20
        queue-capacity: 100
        keep-alive: 60s
  application:
    name: certification-service
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      timeout: 300000
      password: ${REDIS_PASSWORD}
  cloud:
    consul:
      host: consul.synthi-ai.org
      port: 443
      scheme: https
      enabled: true
      discovery:
        enabled: true
        register: true
        service-id: certification-service
        instance-id: certification-service
        health-check-interval: 10s
        tags:
        - version=1.0
        - environment=production
        - secure=true
resilience4j:
  circuitbreaker:
    instances:
      defaultCircuitBreaker:
        slidingWindowSize: 100
        permittedNumberOfCallsInHalfOpenState: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
  timelimiter:
    instances:
      defaultCircuitBreaker:
        timeoutDuration: 5s
management:
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
  tracing:
    sampling:
      probability: 0.1
  metrics:
    tags:
      application: ${spring.application.name}
      environment: production
    distribution:
      percentiles-histogram:
        http.server.requests: true
      sla:
        http.server.requests: 50ms, 100ms, 200ms, 500ms
logging:
  level:
    root: WARN
    org.springframework.cloud: INFO
    org.springframework.kafka: WARN
    org.apache.kafka: WARN
    com.i4u.synthi_ai: INFO
