server:
  port: 9027
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: '{cipher}da83decc14b27fbbf5e1a5a51869b5b4bdd1ddf80ee8a0fa57399c5131f6351069cd2c7b8bf7415aa146f4248b8fb004'
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      max-lifetime: 1800000
      connection-timeout: 30000
      idle-timeout: 600000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  data:
    redis:
      repositories:
        enabled: false
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: '{cipher}53a37b507ec90f4bc4d9743cf2176f9cd9a9c51ce343df07aa1557f1a2108cff'
      timeout: 2000ms
      database: ${REDIS_DATABASE:0}
      lettuce:
        pool:
          max-active: 20
          max-wait: 1000ms
          max-idle: 10
          min-idle: 2
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 2KB
  cache:
    type: redis
    redis:
      cache-null-values: false
      key-prefix: 'legal-service:'
      use-key-prefix: true
    cache-names:
    - public-documents
    - public-document-content
    - document-version-info
    - available-languages
    - available-regions
    - document-metadata
    - consent-statistics
    - user-consent-status
    - markdown-contents
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://20.116.218.195:9020/.well-known/jwks.json
storage:
  minio:
    endpoint: ${MINIO_ENDPOINT:http://20.116.218.195:9000}
    access-key: '{cipher}40be809026f2b4747c30409b4513c9fb94460c3d393702deafcd3d41850cb097'
    secret-key: '{cipher}0c0518b28022fa2e635babbf6d84d171a1890c7b84f23d0d3db8e76b08de13e1'
    bucket-name: ${MINIO_BUCKET_NAME:legal-documents}
    legal-documents-prefix: legal-documents/
messaging:
  kafka:
    topic-prefix: legal-service
legal-service:
  document-defaults:
    language: en
    region: GLOBAL
